// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificacoesService.Infrastructure.Adapters.Output.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificacoesService.Infrastructure.Adapters.Output.Persistence.Migrations
{
    [DbContext(typeof(NotificacaoDbContext))]
    partial class NotificacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificacoesService.Infrastructure.Adapters.Output.Persistence.NotificacaoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("assunto");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid>("DestinatarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("destinatario_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EnviadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviada_em");

                    b.Property<string>("MotivoFalha")
                        .HasColumnType("text")
                        .HasColumnName("motivo_falha");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("TentativasEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("tentativas_envio");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId")
                        .HasDatabaseName("ix_notificacoes_destinatario_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_notificacoes_status");

                    b.ToTable("notificacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
